### ISSUE TITLE
Old Levels from Backup are unaccessible

### ISSUE THREAD

**Issue by IIBriXXII** [Cvolton/GMDprivateServer#971]
Hey there!

so I am currently trying to setup a GDPS based on an older backup. Everything works fine, except you cant download old levels. I tried to change the CHMOD of the data/levels folder and even the levels inside to 777, nothing changed. New levels are downloading normally and you can view comments, leaderboards etc. on the old levels just fine.

After logging into an older Account from the Backup, I wasnt able to load the cloud data either. 

Here is a screenshot of the levels folder, showing that I changed the chmod and that the levels are actually there:
https://imgur.com/k7G2KeW

Thanks in advance ^^

**Comment by Cvolton** [comment]
This is odd, maybe check the server logs if you are able to to see if there are any related errors

**Comment by IIBriXXII** [comment]
I found a "server.php.error.log", however I tried to test around with a new gdps, so the errors in there are related to the new one. I now changed it to the old gdps, however the logs didnt update when I tried to download an older level or load my old save data from the cloud.

I will wait a bit if they update on their own, but if not I would assume that it doesnt throw an php error. Maybe thats just the wrong log file though, but the errors do relate to the gdps files.

**Comment by IIBriXXII** [comment]
Maybe this error actually relates to the old one, so I will post it here just in case

[19-Jan-2023 02:03:08 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) ORDER BY uploadDate DESC LIMIT 10 OFFSET 00' at line 1 in /serverpath/database/incl/levels/getGJLevels.php:242
Stack trace:
#0 /serverpath/database/incl/levels/getGJLevels.php(242): PDOStatement->execute()
#1 /serverpath/database/getGJLevels21.php(2): include('/serverpath/...')
#2 {main}

In the meantime I will test around a bit and see if I can find the error

**Comment by IIBriXXII** [comment]
Okay, I tried to update the database following the _updates/README.md

The only thing that changed is that older Accounts are not accessible anymore, everything new still works perfectly fine.

**Comment by IIBriXXII** [comment]
Is there anything else that I could try?
